theme: minima
title: Code Xstream
author: Christopher 
email: ac18ucs019.christopher.m@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This site is dedicated to bring the right insights and make the users gain 
 the wisdom of practical requrements to be successful in their careers and dreams.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Christ2028 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
